window.DRILL_DATA={
 "MONTHS":[
  ["1月","Januar"],
  ["2月","Februar"],
  ["3月","März"],
  ["4月","April"],
  ["5月","Mai"],
  ["6月","Juni"],
  ["7月","Juli"],
  ["8月","August"],
  ["9月","September"],
  ["10月","Oktober"],
  ["11月","November"],
  ["12月","Dezember"]
 ],
 "TIME_INFORMAL":{
  "0":["{U} Uhr"],
  "5":["fünf nach {N}"],
  "10":["zehn nach {N}"],
  "15":["Viertel nach {N}"],
  "20":["zwanzig nach {N}","zehn vor halb {N2}"],
  "25":["fünf vor halb {N2}"],
  "30":["halb {N2}"],
  "35":["fünf nach halb {N2}"],
  "40":["zwanzig vor {N2}","zehn nach halb {N2}"],
  "45":["Viertel vor {N2}"],
  "50":["zehn vor {N2}"],
  "55":["fünf vor {N2}"]
 },
 "DAYS":[
  ["月曜日","Montag"],
  ["火曜日","Dienstag"],
  ["水曜日","Mittwoch"],
  ["木曜日","Donnerstag"],
  ["金曜日","Freitag"],
  ["土曜日","Samstag",["Sonnabend"]],
  ["日曜日","Sonntag"]
 ],
 "SEASONS":[
  ["春","Frühling",["der Frühling"]],
  ["夏","Sommer",["der Sommer"]],
  ["秋","Herbst",["der Herbst"]],
  ["冬","Winter",["der Winter"]]
 ],
 "DAYPARTS":[
  ["朝","der Morgen",["Morgen"]],
  ["午前","der Vormittag",["Vormittag"]],
  ["昼(正午)","der Mittag",["Mittag"]],
  ["午後","der Nachmittag",["Nachmittag"]],
  ["夕方・晩","der Abend",["Abend"]],
  ["夜","die Nacht",["Nacht"]]
 ],
 "TIMEWORDS":[
  ["今日","heute"],
  ["明日","morgen"],
  ["昨日","gestern"],
  ["あさって","übermorgen"],
  ["おととい","vorgestern"],
  ["今","jetzt"],
  ["今朝","heute Morgen"],
  ["今夜","heute Abend"],
  ["毎日","jeden Tag"],
  ["毎朝","jeden Morgen"],
  ["今週","diese Woche"],
  ["来週","nächste Woche"],
  ["先週","letzte Woche"],
  ["週末","das Wochenende",["Wochenende"]],
  ["月曜日に","am Montag"],
  ["1月に","im Januar"],
  ["夏に","im Sommer"],
  ["朝に","am Morgen"],
  ["夜に","in der Nacht"],
  ["週末に","am Wochenende"],
  ["8時に","um acht Uhr"],
  ["今何時ですか","Wie spät ist es",["Wie viel Uhr ist es"]],
  ["何時に?","Um wie viel Uhr"],
  ["今日は何曜日ですか","Welcher Tag ist heute"],
  ["今日は何日ですか","Der Wievielte ist heute",["Den Wievielten haben wir heute"]]
 ],
 "ART":{
  "定冠詞":{"m":["der","den","dem","des"],"f":["die","die","der","der"],"n":["das","das","dem","des"],"p":["die","die","den","der"]},
  "不定冠詞 ein":{"m":["ein","einen","einem","eines"],"f":["eine","eine","einer","einer"],"n":["ein","ein","einem","eines"],"p":null},
  "否定冠詞 kein / 所有冠詞 mein":{"m":["kein","keinen","keinem","keines"],"f":["keine","keine","keiner","keiner"],"n":["kein","kein","keinem","keines"],"p":["keine","keine","keinen","keiner"]},
  "dieser 型(dieser / jeder / welcher)":{"m":["dieser","diesen","diesem","dieses"],"f":["diese","diese","dieser","dieser"],"n":["dieses","dieses","diesem","dieses"],"p":["diese","diese","diesen","dieser"]}
 },
 "PERS":[
  ["ich","ich","mich","mir","mein"],
  ["du","du","dich","dir","dein"],
  ["er(彼)","er","ihn","ihm","sein"],
  ["sie(彼女)","sie","sie","ihr","ihr"],
  ["es(それ)","es","es","ihm","sein"],
  ["wir","wir","uns","uns","unser"],
  ["ihr(君たち)","ihr","euch","euch","euer"],
  ["sie(彼ら)","sie","sie","ihnen","ihr"],
  ["Sie(あなた)","Sie","Sie","Ihnen","Ihr"]
 ],
 "PRON":[
  "ich",
  "du",
  "er / sie / es",
  "wir",
  "ihr",
  "sie(彼ら)",
  "Sie"
 ],
 "VERBS":{
  "sein":["bin","bist","ist","sind","seid","sind","sind"],
  "haben":["habe","hast","hat","haben","habt","haben","haben"],
  "werden":["werde","wirst","wird","werden","werdet","werden","werden"],
  "wissen":["weiß","weißt","weiß","wissen","wisst","wissen","wissen"],
  "können":["kann","kannst","kann","können","könnt","können","können"],
  "müssen":["muss","musst","muss","müssen","müsst","müssen","müssen"],
  "wollen":["will","willst","will","wollen","wollt","wollen","wollen"],
  "dürfen":["darf","darfst","darf","dürfen","dürft","dürfen","dürfen"],
  "sollen":["soll","sollst","soll","sollen","sollt","sollen","sollen"],
  "mögen":["mag","magst","mag","mögen","mögt","mögen","mögen"]
 },
 "VJA":{
  "sein":"〜である",
  "haben":"持つ",
  "werden":"〜になる",
  "wissen":"知っている",
  "können":"できる",
  "müssen":"〜ねばならない",
  "wollen":"〜したい",
  "dürfen":"〜してよい",
  "sollen":"〜すべき",
  "mögen":"好む"
 },
 "GREET":[
  ["おはよう(おはようございます)","Guten Morgen"],
  ["こんにちは","Guten Tag"],
  ["こんばんは","Guten Abend"],
  ["おやすみなさい","Gute Nacht"],
  ["やあ(くだけた挨拶)","Hallo"],
  ["さようなら","Auf Wiedersehen"],
  ["じゃあね(くだけた別れ)","Tschüss"],
  ["またあとで","Bis später"],
  ["また明日","Bis morgen"],
  ["また近いうちに","Bis bald"],
  ["お元気ですか(敬称 Sie)","Wie geht es Ihnen",["Wie geht's Ihnen"]],
  ["元気?(親称 du)","Wie geht es dir",["Wie geht's dir","Wie geht's"]],
  ["元気です、ありがとう。あなたは?(Sie)","Danke, gut. Und Ihnen",["Danke, gut. Und Ihnen"]],
  ["元気だよ、ありがとう。君は?(du)","Danke, gut. Und dir"],
  ["まあまあです","So lala"],
  ["ありがとう","Danke"],
  ["どうもありがとう","Vielen Dank"],
  ["どういたしまして","Bitte schön",["Gern geschehen","Bitte","Bitte sehr"]],
  ["お願いします / どうぞ","Bitte"],
  ["すみません(呼びかけ・軽い謝罪)","Entschuldigung",["Entschuldigen Sie"]],
  ["ごめんなさい","Es tut mir leid"],
  ["はじめまして(会えてうれしい)","Freut mich",["Angenehm","Freut mich sehr"]],
  ["お名前は?(Sie)","Wie heißen Sie",["Wie ist Ihr Name"]],
  ["名前は?(du)","Wie heißt du"],
  ["私の名前は〜です","Ich heiße",["Mein Name ist"]],
  ["ご出身はどちらですか(Sie)","Woher kommen Sie"],
  ["私は日本出身です","Ich komme aus Japan"],
  ["どこに住んでいますか(Sie)","Wo wohnen Sie"],
  ["私は東京に住んでいます","Ich wohne in Tokyo"],
  ["もう一度お願いします","Noch einmal, bitte",["Noch einmal bitte"]],
  ["何とおっしゃいましたか?","Wie bitte"],
  ["わかりません","Ich verstehe nicht",["Ich verstehe das nicht"]],
  ["ドイツ語を話しますか(Sie)","Sprechen Sie Deutsch"],
  ["少しドイツ語を話します","Ich spreche ein bisschen Deutsch",["Ich spreche etwas Deutsch"]],
  ["乾杯","Prost",["Zum Wohl"]],
  ["召し上がれ(いただきます)","Guten Appetit"],
  ["楽しんでね","Viel Spaß"],
  ["幸運を祈ります","Viel Glück"],
  ["誕生日おめでとう","Alles Gute zum Geburtstag",["Herzlichen Glückwunsch zum Geburtstag"]],
  ["よい週末を","Schönes Wochenende",["Ein schönes Wochenende"]],
  ["お大事に(くしゃみをした人へ)","Gesundheit"],
  ["ようこそ","Herzlich willkommen",["Willkommen"]]
 ],
 "NOUNS":[
  ["der","Mann","男(男性)","Männer"],
  ["der","Vater","父","Väter"],
  ["der","Bruder","兄弟","Brüder"],
  ["der","Tisch","机","Tische"],
  ["der","Stuhl","いす","Stühle"],
  ["der","Hund","犬","Hunde"],
  ["der","Apfel","りんご","Äpfel"],
  ["der","Tag","日","Tage"],
  ["der","Freund","友人(男)","Freunde"],
  ["der","Lehrer","教師(男)","Lehrer"],
  ["der","Kaffee","コーヒー","Kaffees"],
  ["der","Zug","列車","Züge"],
  ["der","Bahnhof","駅","Bahnhöfe"],
  ["der","Käse","チーズ","Käse"],
  ["der","Sohn","息子","Söhne"],
  ["die","Frau","女性・妻","Frauen"],
  ["die","Mutter","母","Mütter"],
  ["die","Schwester","姉妹","Schwestern"],
  ["die","Tür","ドア","Türen"],
  ["die","Katze","猫","Katzen"],
  ["die","Uhr","時計・時","Uhren"],
  ["die","Tasche","かばん","Taschen"],
  ["die","Woche","週","Wochen"],
  ["die","Stadt","都市","Städte"],
  ["die","Schule","学校","Schulen"],
  ["die","Zeit","時間","Zeiten"],
  ["die","Milch","牛乳","(なし)"],
  ["die","Lampe","ランプ","Lampen"],
  ["die","Blume","花","Blumen"],
  ["die","Tochter","娘","Töchter"],
  ["das","Kind","子ども","Kinder"],
  ["das","Buch","本","Bücher"],
  ["das","Haus","家","Häuser"],
  ["das","Auto","車","Autos"],
  ["das","Wasser","水","(なし)"],
  ["das","Fenster","窓","Fenster"],
  ["das","Mädchen","少女","Mädchen"],
  ["das","Brot","パン","Brote"],
  ["das","Bier","ビール","Biere"],
  ["das","Zimmer","部屋","Zimmer"],
  ["das","Jahr","年","Jahre"],
  ["das","Geld","お金","(なし)"],
  ["das","Bett","ベッド","Betten"],
  ["das","Fahrrad","自転車","Fahrräder"],
  ["das","Land","国・土地","Länder"]
 ],
 "ONES":[
  "null",
  "eins",
  "zwei",
  "drei",
  "vier",
  "fünf",
  "sechs",
  "sieben",
  "acht",
  "neun",
  "zehn",
  "elf",
  "zwölf",
  "dreizehn",
  "vierzehn",
  "fünfzehn",
  "sechzehn",
  "siebzehn",
  "achtzehn",
  "neunzehn"
 ],
 "TENS":[
  "",
  "",
  "zwanzig",
  "dreißig",
  "vierzig",
  "fünfzig",
  "sechzig",
  "siebzig",
  "achtzig",
  "neunzig"
 ],
 "ORD_IRREG":{
  "1":"erste",
  "3":"dritte",
  "7":"siebte",
  "8":"achte"
 },
 "PREP":[
  ["statt","2","〜のかわりに","statt meines Vaters","わたしの父のかわりに","anstatt とも言う。口語では 3 格も見られる","5",["anstatt"]],
  ["trotz","2","〜にもかかわらず","trotz des Regens","雨にもかかわらず","口語では 3 格も見られる(trotz dem Regen)","5",[]],
  ["während","2","〜のあいだ(期間)","während des Sommers","夏のあいだ","接続詞「〜する間に」としても使う(während er schläft)","5",[]],
  ["wegen","2","〜のために(理由)","wegen der Kälte","寒さのために","口語では 3 格も見られる(wegen dem Wetter)。目的の「ために」は für","5",[]],
  ["außerhalb","2","〜の外で","außerhalb der Stadt","町の外で","対になる語は innerhalb","",[]],
  ["innerhalb","2","〜の内で、〜以内に","innerhalb einer Woche","1 週間以内に","対になる語は außerhalb","",[]],
  ["aus","3","〜の中から、〜出身の、〜製の","aus dem Haus","家の中から","出身: Ich komme aus Japan. / 素材: aus Holz(木製の)","5",[]],
  ["bei","3","〜のもとで、〜の際に","bei einem Freund","友人のところで","bei dem → beim。beim Essen(食事のときに)","5",[]],
  ["mit","3","〜といっしょに、〜を使って","mit dem Freund","友人といっしょに","手段: mit dem Bus fahren(バスで行く)","5",[]],
  ["nach","3","〜のあとで、(地名)へ","nach dem Essen","食事のあとで","無冠詞の地名へ: nach Deutschland。nach Hause(家へ)は決まった言い方","5",[]],
  ["seit","3","〜以来、〜前から","seit einem Jahr","1 年前から","今も続くことは現在形で言う: Ich lerne seit einem Jahr Deutsch.","",[]],
  ["von","3","〜から、〜の、〜について","von dieser Stelle","この場所から","von dem → vom。受動文の「〜によって」にも使う","5",[]],
  ["zu","3","〜のところへ","zum Bahnhof","駅へ","zu dem → zum、zu der → zur。zu Hause は「家で」(nach Hause は「家へ」)","5",[]],
  ["gegenüber","3","〜の向かいに","gegenüber dem Bahnhof","駅の向かいに","名詞の後にも置ける(dem Bahnhof gegenüber)。代名詞なら必ず後ろ(mir gegenüber)","",[]],
  ["durch","4","〜を通って","durch den Park","公園を通って","原因・手段の「〜によって」にも使う(durch Zufall 偶然に)","5",[]],
  ["für","4","〜のために(目的・利益)","für seine Mutter","彼の母親のために","期間の「〜の予定で」: für eine Woche。理由の「ために」は wegen","5",[]],
  ["gegen","4","〜に向かって、〜に反対して","gegen das Fenster","窓に向かって","時刻の「〜頃」: gegen acht Uhr","5",[]],
  ["ohne","4","〜なしに","ohne Geld","お金なしに","冠詞を付けないことが多い","5",[]],
  ["um","4","〜のまわりに、(時刻)に","um den Tisch","机のまわりに","時刻: um acht Uhr(8 時に)","5",[]],
  ["bis","4","〜まで","bis Montag","月曜日まで","冠詞が要るときは別の前置詞と組み、格はその前置詞が決める: bis zum Bahnhof","",[]],
  ["an","34","〜のきわ(接して)","an der Wand / an die Wand","壁ぎわで(3 格) / 壁ぎわへ(4 格)","an dem → am、an das → ans。曜日・日付は 3 格: am Montag","5",[]],
  ["auf","34","〜の上(接して)","auf dem Tisch / auf den Tisch","机の上で(3 格) / 机の上へ(4 格)","auf das → aufs。warten auf + 4 格(〜を待つ)","5",[]],
  ["hinter","34","〜の後ろ","hinter dem Haus / hinter das Haus","家の後ろで(3 格) / 家の後ろへ(4 格)","","5",[]],
  ["in","34","〜の中","in der Stadt / in die Stadt","町の中で(3 格) / 町の中へ(4 格)","in dem → im、in das → ins。月・季節は 3 格: im Mai / im Sommer","5",[]],
  ["neben","34","〜のかたわら、〜の隣","neben dem Mädchen / neben das Mädchen","少女の隣で(3 格) / 少女の隣へ(4 格)","","5",[]],
  ["über","34","〜の上方(離れて)、〜について","über dem Sofa / über das Sofa","ソファの上方で(3 格) / ソファの上方へ(4 格)","「〜について」は 4 格: über das Wetter sprechen","5",[]],
  ["unter","34","〜の下","unter dem Tisch / unter den Tisch","机の下で(3 格) / 机の下へ(4 格)","「〜の間で(仲間うち)」も 3 格: unter Freunden","5",[]],
  ["vor","34","〜の前","vor dem Haus / vor das Haus","家の前で(3 格) / 家の前へ(4 格)","時を表すときは 3 格: vor dem Essen(食事の前に)、vor drei Tagen(3 日前に)","5",[]],
  ["zwischen","34","〜の間","zwischen den Eltern / zwischen die Eltern","両親の間で(3 格) / 両親の間へ(4 格)","2 つのものを und で並べる: zwischen meinem Vater und meiner Tante","5",[]]
 ],
 "PREP_USE":[
  ["Das Buch liegt auf ___ Tisch.","本が机の上にある","3","dem","場所(静止)→ 3 格。liegen = ある"],
  ["Er legt das Buch auf ___ Tisch.","彼は本を机の上へ置く","4","den","方向(移動)→ 4 格。legen = 置く"],
  ["Er wohnt in ___ Stadt.","彼は町に住んでいる","3","der","場所 → 3 格"],
  ["Er geht in ___ Stadt.","彼は町へ行く","4","die","方向 → 4 格"],
  ["Das Bild hängt an ___ Wand.","絵が壁に掛かっている","3","der","場所 → 3 格。自動詞 hängen = 掛かっている"],
  ["Ich hänge das Bild an ___ Wand.","わたしは絵を壁に掛ける","4","die","日本語は「に」でも、掛ける動作の行き先なので 4 格。他動詞 hängen = 掛ける"],
  ["Die Katze schläft unter ___ Tisch.","猫が机の下で寝ている","3","dem","場所 → 3 格"],
  ["Die Katze läuft unter ___ Tisch.","猫が机の下へ走り込む","4","den","方向 → 4 格"],
  ["Das Auto steht vor ___ Haus.","車が家の前に止まっている","3","dem","場所 → 3 格。stehen = 立っている"],
  ["Er stellt das Auto vor ___ Haus.","彼は車を家の前に止める","4","das","日本語は「に」でも、止める動作の行き先なので 4 格。stellen = 立てて置く"],
  ["Die Lampe hängt über ___ Sofa.","ランプがソファの上方に掛かっている","3","dem","場所 → 3 格"],
  ["Sie sitzt neben ___ Mädchen.","彼女は少女の隣に座っている","3","dem","場所 → 3 格。sitzen = 座っている(状態)"],
  ["Sie setzt sich neben ___ Mädchen.","彼女は少女の隣に座る","4","das","方向 → 4 格。sich setzen = 座る(動作)"],
  ["Der Garten liegt hinter ___ Haus.","庭は家の裏にある","3","dem","場所 → 3 格"],
  ["Der Hund läuft hinter ___ Haus.","犬が家の裏へ走っていく","4","das","方向 → 4 格"],
  ["Der Stuhl steht zwischen ___ Fenstern.","いすが窓と窓の間にある","3","den","場所 → 3 格(複数 3 格は名詞にも -n)"],
  ["Er stellt den Stuhl zwischen ___ Fenster.","彼はいすを窓と窓の間へ置く","4","die","方向 → 4 格(複数 4 格)"],
  ["Er plaudert mit dem Gast in ___ Wohnzimmer.","彼は客と居間でおしゃべりしている","3","dem","場所 → 3 格(in dem は融合して im)"],
  ["Sie geht wieder in ___ Küche.","彼女は再び台所へ行く","4","die","方向 → 4 格"],
  ["Vor ___ Essen mache ich einen Spaziergang.","食事の前にわたしは散歩する","3","dem","時を表す vor は 3 格"],
  ["Wir sprechen über ___ Wetter.","わたしたちは天気について話す","4","das","「〜について」の über は 4 格"],
  ["Ich warte auf ___ Bus.","わたしはバスを待っている","4","den","warten auf + 4 格。動詞と組む前置詞は格が決まっている"]
 ],
 "PREP_FUS":[
  ["in dem","im","3 格(男性・中性)。im Mai / im Wohnzimmer"],
  ["in das","ins","中性 4 格(方向)。ins Kino"],
  ["an dem","am","3 格(男性・中性)。am Montag / am Fenster"],
  ["an das","ans","中性 4 格(方向)。ans Meer"],
  ["auf das","aufs","中性 4 格(方向)。aufs Land"],
  ["zu dem","zum","3 格(男性・中性)。zum Bahnhof"],
  ["zu der","zur","3 格(女性)。zur Schule"],
  ["bei dem","beim","3 格(男性・中性)。beim Essen"],
  ["von dem","vom","3 格(男性・中性)。vom Bahnhof(教材の表にはない)"]
 ],
 "WH":[
  ["誰が","wer"],
  ["誰を","wen"],
  ["誰に","wem"],
  ["誰の","wessen"],
  ["何","was"],
  ["どこ(場所)","wo"],
  ["どこから","woher"],
  ["どこへ","wohin"],
  ["いつ","wann"],
  ["なぜ","warum",["wieso","weshalb"]],
  ["どのように / どう","wie"],
  ["どのくらい(量・値段)","wie viel"],
  ["どのくらい(多数)","wie viele"],
  ["どのくらいの間","wie lange"],
  ["どのくらいの頻度で","wie oft"],
  ["何歳","wie alt"],
  ["どの〜","welcher"],
  ["どんな種類の〜","was für ein"],
  ["何時に","um wie viel Uhr"],
  ["どれ(何の中から)","welches"]
 ],
 "THEMES":[
  {"id":"num1","title":"数字 0〜20","sub":"基数。11〜19 の綴りと 16・17 の変則を固める","kind":"numRange","from":0,"to":20,"parts":[{"table":"onesGrid"},"<ul><li>1 は単独では <b>eins</b>、語の前では <b>ein</b>(ein Uhr / einundzwanzig)</li><li><b>sechs → sechzehn</b>(s が落ちる)、<b>sieben → siebzehn</b>(en が落ちる)</li><li>12 は <b>zwölf</b>、11 は <b>elf</b>(-zehn 型ではない)</li><li>数詞は 1 語でつなげて書く</li></ul>"]},
  {"id":"num2","title":"数字 20〜100","sub":"十の位と「一の位 + und + 十の位」の組み立て","kind":"numRange","from":20,"to":100,"parts":[{"table":"numWords","ns":[20,30,40,50,60,70,80,90,100]},"<ul><li>21〜99 は <b>一の位 + und + 十の位</b>。順序が日本語と逆(21 = einundzwanzig、「1 と 20」)</li><li>一の位の 1 は <b>ein</b>(einundzwanzig)</li><li>30 は <b>dreißig</b>(ß)、60 は <b>sechzig</b>(s が落ちる)、70 は <b>siebzig</b>(en が落ちる)</li><li>例: 47 = siebenundvierzig / 68 = achtundsechzig / 99 = neunundneunzig</li></ul>"]},
  {"id":"num3","title":"数字 100 以上・年号","sub":"hundert・tausend の位と、年の読み方(1100〜1999 は hundert 読み)","kind":"numBig","write":[100,101,110,111,120,200,250,300,365,400,500,666,700,800,900,999,1000,1001,1500,2000,2500,5000,10000,100000],"writeTotal":44,"fillFrom":101,"fillTo":999,"read":[100,200,321,999,1000,2000,10000],"cards":[{"p":"1 000 000","pl":"ドイツ語で書く(名詞)","a":["eine Million"],"show":"eine Million","type":"de","dir":"w"},{"p":"eine Million","pl":"数字で答える","a":["1000000"],"show":"1000000","type":"num","dir":"r","say":1}],"years":[1066,1517,1789,1871,1914,1945,1989,1990,1999,2000,2011,2020,2026],"parts":[{"head":["数","語"],"rows":[["100","hundert / einhundert"],["101","hunderteins"],["200","zweihundert"],["365","dreihundertfünfundsechzig"],["1000","tausend / eintausend"],["2500","zweitausendfünfhundert"],["10000","zehntausend"],["100000","hunderttausend"],["1000000","eine Million(名詞・大文字)"]]},"<ul><li>百の位と十の位の間に <b>und は入れない</b>(123 = hundertdreiundzwanzig)</li><li>1 万・10 万は <b>zehntausend / hunderttausend</b>(万の単位はなく、千の何倍かで言う)</li></ul><h3>年号</h3>",{"head":["年","語"],"rows":[["1990","neunzehnhundertneunzig"],["1871","achtzehnhunderteinundsiebzig"],["2000","zweitausend"],["2026","zweitausendsechsundzwanzig"]]},"<ul><li><b>1100〜1999 年は「◯◯ hundert」読み</b>(19 hundert 90)</li><li><b>2000 年以降は通常の数字の読み</b>(zweitausend…)</li><li>「〜年に」は前置詞なしの <b>1990</b> か <b>im Jahr(e) 1990</b></li></ul>"]},
  {"id":"ord","title":"序数・日付","sub":"1.〜31. の序数と、日付「am 3. Oktober」の 3 格語尾","kind":"ord","to":31,"big":[[100,"hundertste"],[1000,"tausendste"]],"dates":24,"parts":["<ul><li>数字 + <b>ピリオド</b> で序数を表す(3. = dritte)</li><li>〜19 は <b>基数 + te</b>、20 以上は <b>基数 + ste</b></li><li>不規則: <b>1. erste / 3. dritte / 7. siebte / 8. achte</b></li><li>序数は形容詞と同じ語尾がつく(der dritte / am dritten)</li></ul>",{"head":["形","例文"],"rows":[["1 格","Heute ist der dritte Oktober."],["4 格","Den Wievielten haben wir heute? — Den dritten Oktober."],["3 格(〜に)","Ich habe am dritten Oktober Geburtstag."]]},"<p>「○月○日に」は <b>am + 序数(3 格語尾 -n)+ 月名</b>。例: am ersten Mai / am zwanzigsten Juli</p>"]},
  {"id":"time","title":"時刻の言い方","sub":"公式(24時間制)と日常(12時間制・halb / Viertel)","kind":"time","official":20,"informal":20,"parts":["<h3>公式(24 時間制)</h3><p>時 + <b>Uhr</b> + 分。<b>14:35 = vierzehn Uhr fünfunddreißig</b>(0:00 = null Uhr、1 時 = ein Uhr)</p><h3>日常(12 時間制)</h3>",{"head":["時刻","言い方(3 時台)"],"rows":[["3:00","drei Uhr"],["3:05","fünf nach drei"],["3:10","zehn nach drei"],["3:15","Viertel nach drei"],["3:20","zwanzig nach drei / zehn vor halb vier"],["3:25","fünf vor halb vier"],["3:30","<b>halb vier</b>"],["3:35","fünf nach halb vier"],["3:40","zwanzig vor vier / zehn nach halb vier"],["3:45","Viertel vor vier"],["3:50","zehn vor vier"],["3:55","fünf vor vier"]]},"<ul><li><b>halb は「次の時刻に向かって半分」</b>。halb vier = 3:30(4:30 ではない)</li><li>nach / vor の後は数字だけ。<b>「1」は eins</b>(fünf nach eins)、ただし Uhr の前は <b>ein Uhr</b></li><li>問い: <b>Wie spät ist es?</b> / <b>Wie viel Uhr ist es?</b>(今何時)、<b>Um wie viel Uhr …?</b>(何時に)</li><li>答え: <b>Es ist ...</b>(今 …)、<b>um ... Uhr</b>(… 時に)</li></ul>"]},
  {"id":"cal","title":"曜日・月・季節・時間帯","sub":"名詞はすべて男性(Nacht だけ女性)。前置詞 am / im も一緒に","kind":"pairs","src":["DAYS","MONTHS","SEASONS","DAYPARTS","TIMEWORDS"],"parts":["<h3>曜日(すべて der / 男性)</h3>",{"table":"pairs","src":"DAYS"},"<h3>月(すべて der / 男性)</h3>",{"table":"monthsGrid"},"<h3>季節</h3>",{"table":"pairs","src":"SEASONS","prefix":"der "},"<h3>時間帯</h3>",{"table":"pairs","src":"DAYPARTS"},"<h3>副詞・前置詞句</h3>",{"table":"pairs","src":"TIMEWORDS"},"<ul><li>曜日・時間帯 → <b>am</b>(am Montag / am Abend)</li><li>月・季節 → <b>im</b>(im Mai / im Winter)</li><li>時刻 → <b>um</b>(um acht Uhr)</li><li>夜だけ <b>in der Nacht</b></li></ul>"]},
  {"id":"greet","title":"挨拶・日常表現","sub":"あいさつ・お礼・自己紹介・聞き返しの定型句","kind":"pairs","src":["GREET"],"parts":[{"table":"pairs","src":"GREET"},"<ul><li>Sie は敬称(初対面・目上)、du は親称(友人・家族)。Wie geht es Ihnen? / Wie geht es dir?</li><li>入力は大文字小文字と文末の記号(. ! ?)を区別しません</li></ul>"]},
  {"id":"art","title":"冠詞の格変化","sub":"定冠詞・ein・kein / mein・dieser 型(1 格・4 格・3 格・2 格)","kind":"art","parts":[{"table":"art"},"<ul><li>男性の 4 格だけ <b>-en</b>(den / einen / keinen / diesen)</li><li><b>女性・複数の 1 格と 4 格は同形</b>、中性も 1 格 = 4 格</li><li>3 格は m / n が <b>-em</b>、f が <b>-er</b>、複数が <b>-en</b>(名詞にも -n がつく)</li><li>2 格は m / n が <b>-(e)s</b>、f と複数が <b>-er</b>。mein・dein・sein・ihr・unser・euer・Ihr は kein と同じ変化</li><li>複数の ein は存在しない(無冠詞)</li></ul>"]},
  {"id":"noun","title":"名詞の性(der / die / das)","sub":"基本名詞 45 語の冠詞と複数形。性は名詞と一緒に覚える","kind":"noun","parts":["<h3>der(男性)</h3>",{"table":"nouns","art":"der"},"<h3>die(女性)</h3>",{"table":"nouns","art":"die"},"<h3>das(中性)</h3>",{"table":"nouns","art":"das"},"<h3>性の見分け</h3><ul><li><b>die</b>: -ung / -heit / -keit / -schaft / -tion / -ei、-e で終わる語の多く</li><li><b>das</b>: -chen / -lein(縮小)、-ment / -um、動詞の名詞化(das Essen)</li><li><b>der</b>: 男性の人、曜日・月・季節、-er(職業)、-ling</li></ul>"]},
  {"id":"pron","title":"人称代名詞・所有冠詞","sub":"ich・du・er … の 4 格・3 格と、mein・dein … の元の形","kind":"pron","parts":[{"table":"pers"},"<ul><li>er / sie / es は指す名詞の性で決まる(男性名詞 → er / ihn / ihm)</li><li>大文字 <b>Sie / Ihnen / Ihr</b> は敬称(あなた)。文中でも大文字</li><li><b>euer</b> は語尾がつくと e が落ちる(eure Mutter)。<b>unser</b> も unsre と書くことがある</li><li>所有冠詞は kein と同じ語尾(mein Vater / meinen Vater / meiner Mutter)</li></ul>"]},
  {"id":"prep","title":"前置詞と格支配","sub":"前置詞ごとに決まった格(2・3・4・3/4 格)。3・4 格の使い分けと融合形も","kind":"prep","cases":{"2":"2 格","3":"3 格","4":"4 格","34":"3・4 格"},"choices":[["2","2 格","2"],["3","3 格","3"],["4","4 格","4"],["34","3・4 格","5"]],"groups":[["case","格支配(前置詞 → 格)"],["use","3・4 格の使い分け"],["fus","融合形"],["mean","意味 → 前置詞"]],"parts":["<h3>2 格支配</h3>",{"table":"prep","case":"2"},"<h3>3 格支配</h3>",{"table":"prep","case":"3"},"<h3>4 格支配</h3>",{"table":"prep","case":"4"},"<h3>3・4 格支配</h3>",{"table":"prep","case":"34"},"<ul><li><b>場所(静止)→ 3 格</b>: Das Buch liegt auf <b>dem</b> Tisch.(机の上にある)</li><li><b>方向(移動)→ 4 格</b>: Er legt das Buch auf <b>den</b> Tisch.(机の上へ置く)</li><li>問いで確かめる: <b>wo?(どこで)→ 3 格</b> / <b>wohin?(どこへ)→ 4 格</b></li><li>動詞の対: liegen(ある)/ legen(置く)、stehen / stellen、sitzen / setzen、hängen(掛かっている / 掛ける)</li><li>日本語が「に」でも、置く・掛ける動作の行き先なら 4 格(壁に掛ける = an <b>die</b> Wand hängen)</li><li>時を表す an・in・vor は 3 格(am Montag / im Mai / vor dem Essen)</li></ul>","<h3>前置詞と定冠詞の融合形</h3>",{"table":"prepFus"},"<ul><li>融合形はどれも <b>3 格か中性 4 格</b>。in den(男性 4 格)のような形は融合しない</li><li>「その」と強く指すときは融合させない(Ich wohne in dem Haus dort. あそこのその家に住んでいる)</li></ul>","<h3>覚え方</h3><ul><li>3 格支配は <b>aus・bei・mit・nach・seit・von・zu</b>(+ gegenüber)。この順に唱えて覚える</li><li>4 格支配は <b>durch・für・gegen・ohne・um</b>(+ bis)</li><li>2 格支配は <b>statt・trotz・während・wegen</b>。口語では 3 格で使う人も多いが、書くときは 2 格</li><li>3・4 格支配は <b>位置関係を表す 9 つ</b>だけ(an・auf・hinter・in・neben・über・unter・vor・zwischen)</li><li>表の「教材外」は、『練習問題3000題』第 5 章の表にない頻出語</li></ul>"]},
  {"id":"sein","title":"sein・haben・werden の現在変化","sub":"最重要の 3 動詞。不規則なので丸暗記","kind":"verbs","verbs":["sein","haben","werden"],"promptMeaning":false,"skipPersons":[],"parts":[{"table":"verbs","verbs":["sein","haben","werden"],"headMeaning":true},"<ul><li>sein は全く別の形。wir と sie / Sie は <b>sind</b>(3 つ同形)</li><li>haben は du <b>hast</b> / er <b>hat</b>(b が落ちる)</li><li>werden は du <b>wirst</b> / er <b>wird</b>(e→i と語尾)</li></ul>"]},
  {"id":"modal","title":"話法の助動詞・wissen の現在変化","sub":"können・müssen・wollen・dürfen・sollen・mögen・wissen","kind":"verbs","verbs":["wissen","können","müssen","wollen","dürfen","sollen","mögen"],"promptMeaning":true,"skipPersons":[5],"parts":[{"table":"verbs","verbs":["wissen","können","müssen","wollen","dürfen","sollen","mögen"],"headMeaning":false},"<ul><li>単数(ich / er)は <b>語尾なし</b>で同形(ich kann / er kann)</li><li>幹母音が変わるのは単数だけ(können: kann / können、müssen: muss / müssen)</li><li>sollen だけは幹母音が変わらない(soll / sollst / soll)</li><li>wissen も単数で変化する(weiß / weißt / weiß)</li></ul>"]},
  {"id":"wh","title":"疑問詞","sub":"wer・was・wo・wann・warum・wie … の基本と複合形","kind":"pairs","src":["WH"],"parts":[{"table":"pairs","src":"WH"},"<ul><li>wer の格変化: <b>wer</b>(1 格)/ <b>wen</b>(4 格)/ <b>wem</b>(3 格)/ <b>wessen</b>(2 格)</li><li>疑問詞は文頭に置き、<b>動詞は 2 番目</b>(Wo wohnen Sie?)</li><li>wo(場所)/ woher(出所)/ wohin(方向)を区別する</li></ul>"]}
 ]
};
