window.DRILL_DATA={
 "DAYS":[
  ["月曜日","Montag"],
  ["火曜日","Dienstag"],
  ["水曜日","Mittwoch"],
  ["木曜日","Donnerstag"],
  ["金曜日","Freitag"],
  ["土曜日","Samstag",["Sonnabend"]],
  ["日曜日","Sonntag"]
 ],
 "SEASONS":[
  ["春","Frühling",["der Frühling"]],
  ["夏","Sommer",["der Sommer"]],
  ["秋","Herbst",["der Herbst"]],
  ["冬","Winter",["der Winter"]]
 ],
 "DAYPARTS":[
  ["朝","der Morgen",["Morgen"]],
  ["午前","der Vormittag",["Vormittag"]],
  ["昼(正午)","der Mittag",["Mittag"]],
  ["午後","der Nachmittag",["Nachmittag"]],
  ["夕方・晩","der Abend",["Abend"]],
  ["夜","die Nacht",["Nacht"]]
 ],
 "TIMEWORDS":[
  ["今日","heute"],
  ["明日","morgen"],
  ["昨日","gestern"],
  ["あさって","übermorgen"],
  ["おととい","vorgestern"],
  ["今","jetzt"],
  ["今朝","heute Morgen"],
  ["今夜","heute Abend"],
  ["毎日","jeden Tag"],
  ["毎朝","jeden Morgen"],
  ["今週","diese Woche"],
  ["来週","nächste Woche"],
  ["先週","letzte Woche"],
  ["週末","das Wochenende",["Wochenende"]],
  ["月曜日に","am Montag"],
  ["1月に","im Januar"],
  ["夏に","im Sommer"],
  ["朝に","am Morgen"],
  ["夜に","in der Nacht"],
  ["週末に","am Wochenende"],
  ["8時に","um acht Uhr"],
  ["今何時ですか","Wie spät ist es",["Wie viel Uhr ist es"]],
  ["何時に?","Um wie viel Uhr"],
  ["今日は何曜日ですか","Welcher Tag ist heute"],
  ["今日は何日ですか","Der Wievielte ist heute",["Den Wievielten haben wir heute"]]
 ],
 "ART":{
  "定冠詞":{"m":["der","den","dem","des"],"f":["die","die","der","der"],"n":["das","das","dem","des"],"p":["die","die","den","der"]},
  "不定冠詞 ein":{"m":["ein","einen","einem","eines"],"f":["eine","eine","einer","einer"],"n":["ein","ein","einem","eines"],"p":null},
  "否定冠詞 kein / 所有冠詞 mein":{"m":["kein","keinen","keinem","keines"],"f":["keine","keine","keiner","keiner"],"n":["kein","kein","keinem","keines"],"p":["keine","keine","keinen","keiner"]},
  "dieser 型(dieser / jeder / welcher)":{"m":["dieser","diesen","diesem","dieses"],"f":["diese","diese","dieser","dieser"],"n":["dieses","dieses","diesem","dieses"],"p":["diese","diese","diesen","dieser"]}
 },
 "PERS":[
  ["ich","ich","mich","mir","mein"],
  ["du","du","dich","dir","dein"],
  ["er(彼)","er","ihn","ihm","sein"],
  ["sie(彼女)","sie","sie","ihr","ihr"],
  ["es(それ)","es","es","ihm","sein"],
  ["wir","wir","uns","uns","unser"],
  ["ihr(君たち)","ihr","euch","euch","euer"],
  ["sie(彼ら)","sie","sie","ihnen","ihr"],
  ["Sie(あなた)","Sie","Sie","Ihnen","Ihr"]
 ],
 "PRON":[
  "ich",
  "du",
  "er / sie / es",
  "wir",
  "ihr",
  "sie(彼ら)",
  "Sie"
 ],
 "VERBS":{
  "sein":["bin","bist","ist","sind","seid","sind","sind"],
  "haben":["habe","hast","hat","haben","habt","haben","haben"],
  "werden":["werde","wirst","wird","werden","werdet","werden","werden"],
  "wissen":["weiß","weißt","weiß","wissen","wisst","wissen","wissen"],
  "können":["kann","kannst","kann","können","könnt","können","können"],
  "müssen":["muss","musst","muss","müssen","müsst","müssen","müssen"],
  "wollen":["will","willst","will","wollen","wollt","wollen","wollen"],
  "dürfen":["darf","darfst","darf","dürfen","dürft","dürfen","dürfen"],
  "sollen":["soll","sollst","soll","sollen","sollt","sollen","sollen"],
  "mögen":["mag","magst","mag","mögen","mögt","mögen","mögen"]
 },
 "VJA":{
  "sein":"〜である",
  "haben":"持つ",
  "werden":"〜になる",
  "wissen":"知っている",
  "können":"できる",
  "müssen":"〜ねばならない",
  "wollen":"〜したい",
  "dürfen":"〜してよい",
  "sollen":"〜すべき",
  "mögen":"好む"
 },
 "GREET":[
  ["おはよう(おはようございます)","Guten Morgen"],
  ["こんにちは","Guten Tag"],
  ["こんばんは","Guten Abend"],
  ["おやすみなさい","Gute Nacht"],
  ["やあ(くだけた挨拶)","Hallo"],
  ["さようなら","Auf Wiedersehen"],
  ["じゃあね(くだけた別れ)","Tschüss"],
  ["またあとで","Bis später"],
  ["また明日","Bis morgen"],
  ["また近いうちに","Bis bald"],
  ["お元気ですか(敬称 Sie)","Wie geht es Ihnen",["Wie geht's Ihnen"]],
  ["元気?(親称 du)","Wie geht es dir",["Wie geht's dir","Wie geht's"]],
  ["元気です、ありがとう。あなたは?(Sie)","Danke, gut. Und Ihnen",["Danke, gut. Und Ihnen"]],
  ["元気だよ、ありがとう。君は?(du)","Danke, gut. Und dir"],
  ["まあまあです","So lala"],
  ["ありがとう","Danke"],
  ["どうもありがとう","Vielen Dank"],
  ["どういたしまして","Bitte schön",["Gern geschehen","Bitte","Bitte sehr"]],
  ["お願いします / どうぞ","Bitte"],
  ["すみません(呼びかけ・軽い謝罪)","Entschuldigung",["Entschuldigen Sie"]],
  ["ごめんなさい","Es tut mir leid"],
  ["はじめまして(会えてうれしい)","Freut mich",["Angenehm","Freut mich sehr"]],
  ["お名前は?(Sie)","Wie heißen Sie",["Wie ist Ihr Name"]],
  ["名前は?(du)","Wie heißt du"],
  ["私の名前は〜です","Ich heiße",["Mein Name ist"]],
  ["ご出身はどちらですか(Sie)","Woher kommen Sie"],
  ["私は日本出身です","Ich komme aus Japan"],
  ["どこに住んでいますか(Sie)","Wo wohnen Sie"],
  ["私は東京に住んでいます","Ich wohne in Tokyo"],
  ["もう一度お願いします","Noch einmal, bitte",["Noch einmal bitte"]],
  ["何とおっしゃいましたか?","Wie bitte"],
  ["わかりません","Ich verstehe nicht",["Ich verstehe das nicht"]],
  ["ドイツ語を話しますか(Sie)","Sprechen Sie Deutsch"],
  ["少しドイツ語を話します","Ich spreche ein bisschen Deutsch",["Ich spreche etwas Deutsch"]],
  ["乾杯","Prost",["Zum Wohl"]],
  ["召し上がれ(いただきます)","Guten Appetit"],
  ["楽しんでね","Viel Spaß"],
  ["幸運を祈ります","Viel Glück"],
  ["誕生日おめでとう","Alles Gute zum Geburtstag",["Herzlichen Glückwunsch zum Geburtstag"]],
  ["よい週末を","Schönes Wochenende",["Ein schönes Wochenende"]],
  ["お大事に(くしゃみをした人へ)","Gesundheit"],
  ["ようこそ","Herzlich willkommen",["Willkommen"]]
 ],
 "NOUNS":[
  ["der","Mann","男(男性)","Männer"],
  ["der","Vater","父","Väter"],
  ["der","Bruder","兄弟","Brüder"],
  ["der","Tisch","机","Tische"],
  ["der","Stuhl","いす","Stühle"],
  ["der","Hund","犬","Hunde"],
  ["der","Apfel","りんご","Äpfel"],
  ["der","Tag","日","Tage"],
  ["der","Freund","友人(男)","Freunde"],
  ["der","Lehrer","教師(男)","Lehrer"],
  ["der","Kaffee","コーヒー","Kaffees"],
  ["der","Zug","列車","Züge"],
  ["der","Bahnhof","駅","Bahnhöfe"],
  ["der","Käse","チーズ","Käse"],
  ["der","Sohn","息子","Söhne"],
  ["die","Frau","女性・妻","Frauen"],
  ["die","Mutter","母","Mütter"],
  ["die","Schwester","姉妹","Schwestern"],
  ["die","Tür","ドア","Türen"],
  ["die","Katze","猫","Katzen"],
  ["die","Uhr","時計・時","Uhren"],
  ["die","Tasche","かばん","Taschen"],
  ["die","Woche","週","Wochen"],
  ["die","Stadt","都市","Städte"],
  ["die","Schule","学校","Schulen"],
  ["die","Zeit","時間","Zeiten"],
  ["die","Milch","牛乳","(なし)"],
  ["die","Lampe","ランプ","Lampen"],
  ["die","Blume","花","Blumen"],
  ["die","Tochter","娘","Töchter"],
  ["das","Kind","子ども","Kinder"],
  ["das","Buch","本","Bücher"],
  ["das","Haus","家","Häuser"],
  ["das","Auto","車","Autos"],
  ["das","Wasser","水","(なし)"],
  ["das","Fenster","窓","Fenster"],
  ["das","Mädchen","少女","Mädchen"],
  ["das","Brot","パン","Brote"],
  ["das","Bier","ビール","Biere"],
  ["das","Zimmer","部屋","Zimmer"],
  ["das","Jahr","年","Jahre"],
  ["das","Geld","お金","(なし)"],
  ["das","Bett","ベッド","Betten"],
  ["das","Fahrrad","自転車","Fahrräder"],
  ["das","Land","国・土地","Länder"]
 ],
 "WH":[
  ["誰が","wer"],
  ["誰を","wen"],
  ["誰に","wem"],
  ["誰の","wessen"],
  ["何","was"],
  ["どこ(場所)","wo"],
  ["どこから","woher"],
  ["どこへ","wohin"],
  ["いつ","wann"],
  ["なぜ","warum",["wieso","weshalb"]],
  ["どのように / どう","wie"],
  ["どのくらい(量・値段)","wie viel"],
  ["どのくらい(多数)","wie viele"],
  ["どのくらいの間","wie lange"],
  ["どのくらいの頻度で","wie oft"],
  ["何歳","wie alt"],
  ["どの〜","welcher"],
  ["どんな種類の〜","was für ein"],
  ["何時に","um wie viel Uhr"],
  ["どれ(何の中から)","welches"]
 ]
};
